"""커피 카페인 함량 참고 데이터 (브랜드별/메뉴별/사이즈별).

단일 진실 공급원(single source of truth) 원칙 — 이 파일 외 다른 곳에 중복 데이터를
두지 않는다 (nutrition_constants.py 패턴 참조).

NULL != 0 원칙: caffeine_mg를 확인하지 못한 조합은 아예 항목을 만들지 않는다
(추정/보간 금지). 확인하지 못한 조합 목록은 이 파일 하단 주석과 리서치 리포트에
별도로 기록되어 있으며, 여기 없는 브랜드+메뉴+사이즈 조합은 "0mg"이 아니라
"미확인"으로 해석해야 한다.

source_tier: 1 = 브랜드 공식 발표, 2 = 정부/공공기관(식약처·한국소비자원) 실측치,
3 = 독립 매체/블로그 (최소 2개 이상의 상호 corroborate된 출처가 있는 경우만 채택).

volume_ml이 None인 항목은 브랜드가 공식적으로 용량(ml)을 공개하지 않아 카페인
수치만 확인되었음을 의미한다 (추정 금지, 아래 주석 참고).

verified_date는 이 리서치 패스에서 원본 소스를 실제로 확인한 날짜다.
"""

COFFEE_CAFFEINE_DATA = [
    # ── 스타벅스 (Starbucks Korea) — Tier 1, starbucks.co.kr 공식 상품 페이지 ──
    # 주의: 스타벅스는 공식 페이지에 Tall(355ml) 기준 수치만 게시하며
    # Short/Grande/Venti 사이즈별 수치는 어디에도 공개되어 있지 않음 (gap).
    # 디카페인 대체 수치도 공식적으로 공개되지 않음 (블로그 수치만 존재, 단일 출처로 미채택).
    {
        "brand": "스타벅스",
        "menu": "카페 아메리카노",
        "size": "Tall",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 150,
        "source_tier": 1,
        "source_url": "https://www.starbucks.co.kr/menu/drink_view.do?product_cd=94",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "스타벅스",
        "menu": "카페 아메리카노",
        "size": "Tall",
        "volume_ml": 355,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 150,
        "source_tier": 1,
        "source_url": "https://www.starbucks.co.kr/menu/drink_view.do?product_cd=110563",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "스타벅스",
        "menu": "카페 라떼",
        "size": "Tall",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 75,
        "source_tier": 1,
        "source_url": "https://www.starbucks.co.kr/menu/drink_view.do?product_cd=41",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "스타벅스",
        "menu": "카페 라떼",
        "size": "Tall",
        "volume_ml": 355,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 75,
        "source_tier": 1,
        "source_url": "https://www.starbucks.co.kr/menu/drink_view.do?product_cd=110569",
        "verified_date": "2026-07-30",
    },

    # ── 메가MGC커피 (Mega MGC Coffee) — Tier 1, 공식 영양성분표(26.07.24 ver) + 메뉴 페이지 ──
    # 메가리카노/왕메가카페라떼는 ICE 전용 (HOT 버전 없음 — 미판매, gap 아님).
    {
        "brand": "메가MGC커피",
        "menu": "아메리카노",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 204.2,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "아메리카노",
        "size": "기본",
        "volume_ml": 710,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 199.7,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "메가리카노",
        "size": "메가",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 290.8,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
        "note": "공식 페이지 설명 텍스트는 960ml로 표기하나 영양정보 모달 수치는 946ml — 두 값 모두 공식 페이지에 존재.",
    },
    {
        "brand": "메가MGC커피",
        "menu": "카페라떼",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 189.9,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "카페라떼",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 199.1,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "왕메가카페라떼",
        "size": "왕메가",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 347.1,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "디카페인 아메리카노",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 11.4,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "디카페인 아메리카노",
        "size": "기본",
        "volume_ml": 710,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 10.8,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "디카페인 메가리카노",
        "size": "메가",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 10.9,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "디카페인 카페라떼",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 17.0,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "메가MGC커피",
        "menu": "디카페인 카페라떼",
        "size": "기본",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 14.4,
        "source_tier": 1,
        "source_url": "https://www.mega-mgccoffee.com/bbs/detail/?bbs_idx=198",
        "verified_date": "2026-07-30",
    },

    # ── 빽다방 (Paik's Coffee) — Tier 1, paikdabang.com 공식 메뉴/영양정보 ──
    # 사전 리서치 리드(기본 237mg/빽사이즈 474mg)는 공식 페이지와 불일치하여 폐기, 아래 공식값으로 대체.
    {
        "brand": "빽다방",
        "menu": "아메리카노",
        "size": "기본",
        "volume_ml": 510,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 197,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "아메리카노",
        "size": "기본",
        "volume_ml": 660,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 166,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "디카페인 아메리카노",
        "size": "기본",
        "volume_ml": 510,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 1.0,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "디카페인 아메리카노",
        "size": "기본",
        "volume_ml": 660,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 1.2,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "카페라떼",
        "size": "기본",
        "volume_ml": 510,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 152,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "카페라떼",
        "size": "기본",
        "volume_ml": 660,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 163,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "디카페인 카페라떼",
        "size": "기본",
        "volume_ml": 510,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 0.8,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "디카페인 카페라떼",
        "size": "기본",
        "volume_ml": 660,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 0.7,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        # 빽사이즈는 ICE 전용 (HOT 미판매)
        "brand": "빽다방",
        "menu": "아메리카노",
        "size": "빽사이즈",
        "volume_ml": 990,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 293,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "카페라떼",
        "size": "빽사이즈",
        "volume_ml": 990,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 286,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "빽다방",
        "menu": "디카페인 아메리카노",
        "size": "빽사이즈",
        "volume_ml": 990,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 1.6,
        "source_tier": 1,
        "source_url": "https://paikdabang.com/menu/menu_coffee/",
        "verified_date": "2026-07-30",
    },

    # ── 할리스 (Hollys Coffee) — Tier 1, hollys.co.kr 공식 영양정보 ──
    # 공식 페이지는 사이즈(레귤러/그란데/벤티)·온도(HOT/ICE) 구분 없이 메뉴당 단일 카페인
    # 수치만 게시함 (사전 리드의 114/171/228mg 사이즈별 차등은 공식 페이지와 불일치하여 폐기).
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "레귤러",
        "volume_ml": 354,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "그란데",
        "volume_ml": 472,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "벤티",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "레귤러",
        "volume_ml": 354,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "그란데",
        "volume_ml": 472,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "아메리카노",
        "size": "벤티",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 114,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=6",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "레귤러",
        "volume_ml": 354,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "그란데",
        "volume_ml": 472,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "벤티",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "레귤러",
        "volume_ml": 354,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "그란데",
        "volume_ml": 472,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },
    {
        "brand": "할리스",
        "menu": "카페라떼",
        "size": "벤티",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 127,
        "source_tier": 1,
        "source_url": "https://m.hollys.co.kr/menu/menuView.do?menuDiv=ESPRESSO&idx=12",
        "verified_date": "2026-07-30",
        "note": "공식 표는 사이즈/온도 구분 없이 동일 수치 게시.",
    },

    # ── 커피빈 (The Coffee Bean & Tea Leaf Korea) — Tier 1, coffeebeankorea.com 공식 메뉴 ──
    # 공식 페이지에 카페인(mg)만 게시되고 용량(ml)은 공개되지 않음 (volume_ml=None, gap).
    # "아메리카노"라는 이름의 메뉴는 현재 폐지되었고 "커피빈카노"가 그 자리를 대체함.
    {
        "brand": "커피빈",
        "menu": "커피빈카노",
        "size": None,
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 172,
        "source_tier": 1,
        "source_url": "https://www.coffeebeankorea.com/menu/list.asp?category=13",
        "verified_date": "2026-07-30",
        "note": "브랜드 공식 페이지에 용량(ml) 미공개 — 서드파티가 언급하는 355ml는 브랜드 자체 확인 불가.",
    },
    {
        "brand": "커피빈",
        "menu": "커피빈카노",
        "size": None,
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 172,
        "source_tier": 1,
        "source_url": "https://www.coffeebeankorea.com/menu/list.asp?category=13",
        "verified_date": "2026-07-30",
        "note": "브랜드 공식 페이지에 용량(ml) 미공개.",
    },
    {
        "brand": "커피빈",
        "menu": "커피빈라떼",
        "size": None,
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 172,
        "source_tier": 1,
        "source_url": "https://www.coffeebeankorea.com/menu/list.asp?category=13",
        "verified_date": "2026-07-30",
        "note": "브랜드 공식 페이지에 용량(ml) 미공개.",
    },
    {
        "brand": "커피빈",
        "menu": "커피빈라떼",
        "size": None,
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 172,
        "source_tier": 1,
        "source_url": "https://www.coffeebeankorea.com/menu/list.asp?category=13",
        "verified_date": "2026-07-30",
        "note": "브랜드 공식 페이지에 용량(ml) 미공개.",
    },

    # ── 컴포즈커피 (Compose Coffee) — Tier 1, 공식 공지사항 영양성분표 ──
    {
        "brand": "컴포즈커피",
        "menu": "아메리카노",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 185.81,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "아메리카노",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 185.81,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        # 빅포즈(32oz)는 ICE 전용
        "brand": "컴포즈커피",
        "menu": "아메리카노",
        "size": "빅포즈(32oz)",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 371.62,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "카페라떼",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 247.75,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "카페라떼",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 247.75,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 9.16,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 9.16,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "빅포즈(32oz)",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 18.32,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 12.21,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "일반(20oz)",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 12.21,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "컴포즈커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "빅포즈(32oz)",
        "volume_ml": 946,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 24.43,
        "source_tier": 1,
        "source_url": "https://composecoffee.com/notice/112590",
        "verified_date": "2026-07-30",
    },

    # ── 이디야커피 (Ediya Coffee) — 카페인 mg는 Tier 1 (ediya.com 공식 영양정보 모달) ──
    # 라지(L) 용량은 Tier 3 (2025-12-16 사이즈 개편 보도, 2개 이상 매체 corroborate).
    # 엑스트라(EX) 용량은 매체마다 상이하여 미확인 (volume_ml=None, gap).
    {
        "brand": "이디야커피",
        "menu": "아메리카노",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 158,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "용량 532ml(18oz)은 Tier 3 (zdnet.co.kr 등 2025-12-16 사이즈 개편 보도 corroborate).",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 158,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "용량 532ml(18oz)은 Tier 3 corroborate.",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 237,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml)은 매체마다 상이 (22~23oz 통칭 외 650/680/709ml 등 불일치) — 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 237,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 158,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "용량 532ml(18oz)은 Tier 3 corroborate.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 158,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "용량 532ml(18oz)은 Tier 3 corroborate.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 237,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 237,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 9,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "HOT/ICE 동일 수치 (사이트 자체가 온도 구분 없이 디카페인 대체 수치를 단일 게시).",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 9,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 13,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "아메리카노 (디카페인 원두 변경)",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 13,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 9,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "라지(L)",
        "volume_ml": 532,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 9,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "hot",
        "is_decaf": True,
        "caffeine_mg": 13,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },
    {
        "brand": "이디야커피",
        "menu": "카페라떼 (디카페인 원두 변경)",
        "size": "엑스트라(EX)",
        "volume_ml": None,
        "hot_or_ice": "ice",
        "is_decaf": True,
        "caffeine_mg": 13,
        "source_tier": 1,
        "source_url": "https://ediya.com/contents/drink.html?chked_val=12,",
        "verified_date": "2026-07-30",
        "note": "EX 용량(ml) 미확인.",
    },

    # ── 투썸플레이스 (A Twosome Place) — Tier 1, 공식 영양성분표 이미지 (2026-07-15 게시) ──
    # 원두 2종 판매: 블랙그라운드(기본) / 아로마노트(변경 옵션) — menu 필드로 구분.
    # HOT은 R/L만 존재 (Max는 ICE 전용). 순수 아메리카노/라떼의 디카페인 수치는 미공개
    # (공식 자료엔 "디카페인 오트 화이트 라떼"라는 가향 메뉴의 디카페인 수치만 존재 — 범위 밖).
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노",
        "size": "R",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 186,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노 (아로마노트 원두 변경)",
        "size": "R",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 214,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 279,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노 (아로마노트 원두 변경)",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 321,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노",
        "size": "R",
        "volume_ml": 414,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 186,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노 (아로마노트 원두 변경)",
        "size": "R",
        "volume_ml": 414,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 214,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 279,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노 (아로마노트 원두 변경)",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 321,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노",
        "size": "M",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 372,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "아메리카노 (아로마노트 원두 변경)",
        "size": "M",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 428,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼",
        "size": "R",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 186,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼 (아로마노트 원두 변경)",
        "size": "R",
        "volume_ml": 355,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 214,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 279,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼 (아로마노트 원두 변경)",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "hot",
        "is_decaf": False,
        "caffeine_mg": 321,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼",
        "size": "R",
        "volume_ml": 414,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 186,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼 (아로마노트 원두 변경)",
        "size": "R",
        "volume_ml": 414,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 214,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 279,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼 (아로마노트 원두 변경)",
        "size": "L",
        "volume_ml": 473,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 321,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼",
        "size": "M",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 372,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },
    {
        "brand": "투썸플레이스",
        "menu": "카페라떼 (아로마노트 원두 변경)",
        "size": "M",
        "volume_ml": 591,
        "hot_or_ice": "ice",
        "is_decaf": False,
        "caffeine_mg": 428,
        "source_tier": 1,
        "source_url": "https://mcdn.twosome.co.kr/upload/home/inform/nutrient_260715.jpg",
        "verified_date": "2026-07-30",
    },

    # 파스쿠찌(Pascucci)는 이번 리서치에서 Tier 1/2/3 기준을 만족하는 값을 찾지 못해
    # 전체 브랜드를 제외했다 — 공식 공지는 이미지 전용이라 수치 추출 불가했고,
    # 한국소비자원 실측치는 2012년(152mg)과 2018년(약 196~202mg)이 30% 이상 차이나
    # "conflicting sources"로 판단, 라떼/사이즈/용량 데이터는 전무함. 하단 문서 참고.
]

# 홈메이드 커피 (브랜드 무관 고정 프리셋)
# 원두커피/커피믹스/인스턴트커피 수치는 모두 2020년 식약처 산하 식품의약품안전평가원의
# "국내 유통식품 21품목 883건 카페인 함량 조사" (Tier 2, 원 보도자료는 이번 검색에서
# 직접 확인하지 못함) 수치이며, 서로 무관한 다수의 매체가 동일 수치를 인용해
# corroborate되어 Tier 3로 채택했다.
HOME_COFFEE_PRESETS = [
    {
        "brand": "홈메이드 커피",
        "menu": "원두커피/드립커피",
        "serving": "약 7g (원두 기준)",
        "caffeine_mg": 91.5,
        "source_tier": 3,
        "source_url": "https://medicalworldnews.co.kr/m/view.php?idx=1510934725",
        "verified_date": "2026-07-30",
        "note": "원 출처는 2020년 식약처 식품의약품안전평가원 조사(원문 미확인, 다수 매체 corroborate).",
    },
    {
        "brand": "홈메이드 커피",
        "menu": "커피믹스",
        "serving": "1회분 (약 12g)",
        "caffeine_mg": 55.8,
        "source_tier": 3,
        "source_url": "https://medicalworldnews.co.kr/m/view.php?idx=1510934725",
        "verified_date": "2026-07-30",
        "note": "원 출처는 2020년 식약처 식품의약품안전평가원 조사(원문 미확인, 다수 매체 corroborate).",
    },
    {
        "brand": "홈메이드 커피",
        "menu": "인스턴트커피",
        "serving": "1회분 (약 2g)",
        "caffeine_mg": 54.5,
        "source_tier": 3,
        "source_url": "https://medicalworldnews.co.kr/m/view.php?idx=1510934725",
        "verified_date": "2026-07-30",
        "note": "원 출처는 2020년 식약처 식품의약품안전평가원 조사(원문 미확인, 다수 매체 corroborate).",
    },
]
